### ISSUE TITLE
path must be a string or Buffer

### ISSUE THREAD

**Issue by maoo** [finos/cla-bot#7]
When running `npm run execute` I get the following:

```
> cla-bot@1.0.0 execute /Users/m/w/projects/cla-bot
> node-lambda run --configFile deploy.env

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/Users/m/w/projects/cla-bot/installationToken.js:7:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

My `deploy.env` looks includes:
```
GITHUB_ACCESS_TOKEN=--token--
INTEGRATION_ENABLED=false
```

Submitting PR to avoid `const` init, if `process.env.INTEGRATION_KEY` is not set.

**Comment by maoo** [comment]
Issue fixed on develop branch
