### ISSUE TITLE
cla-bot-logs deployment - Cannot read property 'Items' of null

### ISSUE THREAD

**Issue by maoo** [finos/cla-bot#83]
Hi,

I'm trying to deploy the `cla-bot-logs` module, but it fails trying to resolve the `correlationKey` against the DynamoDB:

```
2018-03-19T17:53:58.607Z	7f23cdb2-2b9e-11e8-a4fb-3998bce88dc7	TypeError: Cannot read property 'Items' of null
at Response.dynamodb.query (/var/task/index.js:23:22)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)
```

The issue refers to [this code block](https://github.com/ColinEberhardt/cla-bot/blob/develop/cla-bot-logs/index.js#L20):
```
  dynamodb.query(params, (err, data) => {
    data.Items = data.Items.filter(d => d.level !== 'DEBUG');
    if (err) {
      console.log(err, err.stack);
    } else {
      loggingCallback(null, data.Items);
    }
  });
```

I know - by adding `console.info` statements, that `correlationKey` and `process.env.LOGGING_TABLE` are correctly resolved (which means [lambda mapping template](https://gist.github.com/maoo/16b4a683e8cf9ae4b466ace0ae745497#8-create-aws-api-gateway-api) should be correctly defined); I've also added full access on DynamoDB tables to the AWS IAM role used to connect the AWS Lambda function with the API Gateway, to exclude permission issues.

Any idea what may be wrong with my setup?
Thanks!

**Comment by maoo** [comment]
Hi Colin and thanks for the answer!

Yes, the LOGGING_TABLE exists and contains logging entries, the problem
occurs when I try to access the logs.

I changed the code as you suggested, and here's the smoking gun (details below): `ValidationException: Query condition missed key schema element: uuid`

I think the problem is the way I created the DynamoDB table, which was simply to define:
- Table Name: cla-bot-logs
- Primary Key: uuid
- Uncheck `Add sort key`
- Check `Use default settings`

Do you see any step missing here?

Full error stack:
```
2018-03-28T10:25:32.570Z	57aff54b-3272-11e8-a94f-4d8b4f73c2e3	{ ValidationException: Query condition missed key schema element: uuid
at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'Query condition missed key schema element: uuid',
code: 'ValidationException',
```

**Comment by maoo** [comment]
Found the issue; I created the DynamoDB with the primaryKey `correlationKey` and sortKey `time` and everything works now, see screenshot below.

Thanks for your help @ColinEberhardt !

![screen shot 2018-04-02 at 10 45 56](https://user-images.githubusercontent.com/327285/38190364-217a3e4c-3664-11e8-8e4e-fc3434a511a7.png)
